FROM alpine

RUN apk update
RUN apk add --no-cache \
        mosquitto \
        openssl \
        python3 \
        py3-pip \
        curl-dev \
    && apk add --no-cache --virtual .build-dependencies \
        build-base \
        git \
        mosquitto-dev \
        openssl-dev \
        libc-dev \
        python3-dev \
    \
    && git clone --depth 1 \
        https://github.com/pvizeli/mosquitto-auth-plug \
    && cd mosquitto-auth-plug \
    && cp config.mk.in config.mk \
    && make \
    && mkdir -p /usr/share/mosquitto \
    && cp -f auth-plug.so /usr/share/mosquitto \
    && rm -fr /usr/src/mosquitto-auth-plug 
EXPOSE 1883
EXPOSE 9090
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirement.txt
RUN apk del .build-dependencies
COPY run.sh run.sh
COPY app app
